[package]
name = "wav-decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.0"
crossbeam-queue = "0.3.8"
simple-bytes = "0.2.11"
termion = "2.0.1"
